/* ============================================================
   script.js — load a chapter and resolve its cues to real times.

   A chapter is authored as prose with cues pinned to *words*:

       { "on": "word:Concord", "do": "map.flyTo", "to": "concord" }

   The narration tool records when every word was actually spoken, so this
   module turns those anchors into absolute seconds within a scene's audio.
   Nothing in the authored file is hand-timed, which means a rewrite or a
   change of voice only requires re-running the tool.
   ============================================================ */

/** Anchors we understand on a cue's `on` field. */
const ANCHOR = {
  START: 'start',
  END: 'end',
};

export async function loadChapter(pack, chapterId, lang) {
  const base = `./content/${pack}`;
  const [chapter, timing, media] = await Promise.all([
    getJSON(`${base}/${chapterId}.json`),
    getJSON(`${base}/timing.${lang}.json`).catch(() => null),
    // media.json is generated by tools/fetch-media.py, so it lives beside the
    // chapter rather than inside it — regenerating images must not rewrite prose.
    getJSON(`${base}/media.json`).catch(() => ({})),
  ]);
  if (!chapter) throw new Error(`chapter ${chapterId} could not be loaded`);
  return compile({ ...chapter, media: media || {} }, timing, lang, base);
}

async function getJSON(url) {
  const res = await fetch(url, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

/* ------------------------------------------------------------
   Compile
   ------------------------------------------------------------ */

function compile(chapter, timing, lang, base) {
  const warnings = [];
  const scenes = chapter.scenes.map((scene) => {
    const t = timing?.scenes?.[scene.id];
    const beats = scene.beats.map((beat) => {
      const bt = t?.beats?.find((b) => b.id === beat.id);
      return {
        id: beat.id,
        text: pick(beat.say, lang),
        start: bt?.start ?? 0,
        dur: bt?.dur ?? 0,
        gapAfter: bt?.gapAfter ?? beat.gapAfter ?? 0,
        words: bt?.words ?? [],
        raw: beat,
      };
    });

    // Flatten every cue in the scene onto one timeline.
    const cues = [];
    for (const beat of beats) {
      for (const cue of beat.raw.cues || []) {
        // An anchor may be a bare string when it works in every language
        // (proper nouns usually do), or a {no, en} pair when the languages
        // say it differently — "syttisju" is "seventy-seven" over there.
        const at = resolve(pick(cue.on ?? 'start', lang), beat, warnings);
        cues.push({ ...cue, t: at, beat: beat.id });
      }
    }
    // Stable sort: equal times keep their authored order, which matters when a
    // beat clears something and immediately sets it again.
    cues.forEach((c, i) => { c._i = i; });
    cues.sort((a, b) => (a.t - b.t) || (a._i - b._i));

    const last = beats[beats.length - 1];
    return {
      id: scene.id,
      title: pick(scene.title, lang),
      clock: pick(scene.clock, lang),
      audio: t ? `${base}/${t.audio}` : null,
      dur: t?.dur ?? (last ? last.start + last.dur : 0),
      beats,
      cues,
    };
  });

  if (warnings.length) {
    console.warn(`[script] ${warnings.length} cue anchor(s) could not be resolved:`);
    for (const w of warnings) console.warn('  ' + w);
  }

  return {
    id: chapter.id,
    pack: chapter.pack,
    lang,
    title: pick(chapter.title, lang),
    subtitle: pick(chapter.subtitle, lang),
    blurb: pick(chapter.blurb, lang),
    places: chapter.places || {},
    routes: chapter.routes || {},
    media: chapter.media || {},
    quotes: chapter.quotes || {},
    poster: chapter.poster || null,
    scenes,
    duration: scenes.reduce((n, s) => n + s.dur, 0),
    hasAudio: Boolean(timing),
    warnings,
  };
}

function pick(field, lang) {
  if (field == null) return '';
  if (typeof field === 'string') return field;
  return field[lang] ?? field.no ?? field.en ?? '';
}

/* ------------------------------------------------------------
   Anchor resolution
   ------------------------------------------------------------ */

/** Strip punctuation and case so "Concord," matches "concord". */
function norm(s) {
  return String(s).toLowerCase().replace(/[^\p{L}\p{N}]/gu, '');
}

function resolve(on, beat, warnings) {
  const spec = on || ANCHOR.START;

  if (spec === ANCHOR.START) return beat.start;
  if (spec === ANCHOR.END) return beat.start + beat.dur;

  if (spec.startsWith('t:')) {
    return beat.start + (parseFloat(spec.slice(2)) || 0);
  }
  if (spec.startsWith('pct:')) {
    return beat.start + (parseFloat(spec.slice(4)) || 0) * beat.dur;
  }
  if (spec.startsWith('word:')) {
    // "word:Concord" or "word:Concord#2" for the second occurrence
    const [wanted, nth] = spec.slice(5).split('#');
    const target = norm(wanted);
    const want = Math.max(1, parseInt(nth || '1', 10));
    let seen = 0;
    for (const w of beat.words) {
      if (norm(w.w) === target && ++seen === want) return w.t;
    }
    warnings.push(`${beat.id}: no word "${wanted}"${nth ? ` #${nth}` : ''} in "${beat.text.slice(0, 60)}…"`);
    return beat.start;   // fall back to the beat opening rather than dropping it
  }

  warnings.push(`${beat.id}: unknown anchor "${spec}"`);
  return beat.start;
}

/** Which beat is playing at time t (for captions). */
export function beatAt(scene, t) {
  let found = null;
  for (const b of scene.beats) {
    if (t >= b.start) found = b; else break;
  }
  return found;
}

/** Index of the word being spoken at time t, or -1 between words. */
export function wordAt(beat, t) {
  if (!beat) return -1;
  for (let i = 0; i < beat.words.length; i++) {
    const w = beat.words[i];
    if (t >= w.t && t < w.t + w.d + 0.06) return i;
    if (t < w.t) return i - 1;   // in the gap before this word
  }
  return beat.words.length - 1;
}
