/* ============================================================
   script.js — load a chapter and resolve its cues to real times.

   A chapter is authored as prose with cues pinned to *words*:

       { "on": "word:Concord", "do": "map.flyTo", "to": "concord" }

   The narration tool records when every word was actually spoken, so this
   module turns those anchors into absolute seconds within a scene's audio.
   Nothing in the authored file is hand-timed, which means a rewrite or a
   change of voice only requires re-running the tool.
   ============================================================ */

import { loadPack } from './pack.js';
import { packBase } from '../core/paths.js';

/** Anchors we understand on a cue's `on` field. */
const ANCHOR = {
  START: 'start',
  END: 'end',
};

export async function loadChapter(pack, chapterId, lang) {
  const base = packBase(pack);
  const packInfo = await loadPack(pack);
  const pools = packInfo?.pools || {};
  const pool = (name, fallback) => (pools[name]
    ? getJSON(`${base}/${pools[name]}`).catch(() => fallback)
    : Promise.resolve(fallback));

  // Everything the chapter needs, in one wave.
  //
  // The depth pools are here rather than fetched when a reader taps something,
  // and that is load-bearing: an await inside a cue handler is how a `clear`
  // in a later beat ran before an earlier `show` resolved and left
  // Massachusetts washed blue over the whole map. Nothing that a cue touches
  // may arrive late, so none of it is fetched late.
  const [chapter, media, terms, topics, placeNotes, people] = await Promise.all([
    getJSON(`${base}/${chapterId}.json`),
    // media.json is generated by tools/fetch-media.py, so it lives beside the
    // chapter rather than inside it — regenerating images must not rewrite prose.
    getJSON(`${base}/media.json`).catch(() => ({})),
    pool('terms', {}),
    pool('topics', {}),
    pool('placeNotes', {}),
    // People are a PACK pool, not something handed in from outside. They used
    // to arrive as an argument from js/main.js, which loads the default pack —
    // so opening a chapter from a second pack looked up Octavian in a list of
    // American revolutionaries and drew nothing at all.
    pool('people', []),
  ]);
  if (!chapter) throw new Error(`chapter ${chapterId} could not be loaded`);

  // A chapter is only narrated in the languages that have been recorded. If the
  // reader's language is not one of them, fall back to one that is rather than
  // loading a chapter with no durations, where every word-anchored cue would
  // collapse to the start of its beat and the whole thing would run silent.
  // Which languages are actually RECORDED. The pack says so per chapter, and
  // an empty list means none yet — so a chapter still being authored is run on
  // the timer instead of asking the network for four files that do not exist
  // and logging four 404s on the way past.
  const declared = (packInfo?.chapters || []).find((c) => c.id === chapterId)?.langs;
  const offered = Array.isArray(declared) ? declared : Object.keys(chapter.voice || {});
  const order = [lang, ...offered.filter((l) => l !== lang)].filter(
    (l) => !Array.isArray(declared) || declared.includes(l));
  let timing = null;
  let narrationLang = lang;
  for (const candidate of order) {
    // Keyed by chapter as well as language: scene ids restart at s0 in every
    // chapter, so one file per pack had chapter two overwriting chapter one.
    timing = await getJSON(`${base}/timing.${chapterId}.${candidate}.json`).catch(() => null);
    if (timing) { narrationLang = candidate; break; }
  }
  if (!timing) {
    console.warn(`[script] ${chapterId} has no recorded narration in any language`);
  } else if (narrationLang !== lang) {
    console.warn(`[script] no ${lang} narration for ${chapterId}; using ${narrationLang}`);
  }

  return compile({
    ...chapter,
    media: media || {},
    packInfo: packInfo || null,
    terms: terms || {},
    topics: topics || {},
    placeNotes: placeNotes || {},
    people: people || [],
  }, timing, narrationLang, base, lang);
}

async function getJSON(url) {
  const res = await fetch(url, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

/* ------------------------------------------------------------
   Compile
   ------------------------------------------------------------ */

function compile(chapter, timing, lang, base, uiLang = lang) {
  const warnings = [];

  /* How fast the voice would have read this, if it had.
     A chapter with no recording used to compile to a duration of zero: every
     beat started at 0 and lasted 0, so the whole thing was over before it
     began and none of the cues could fire. That made it impossible to author
     a chapter the way the authoring order says to — cues and captions first,
     narration last — because there was nothing to watch until the audio
     existed.
     So an unrecorded beat is given an estimated duration from its word count
     at the pack's speaking rate. It is an estimate and the captions cannot
     highlight word by word, but the chapter RUNS, and that is the difference
     between a draft you can watch and a draft you cannot. */
  const wps = (chapter.packInfo?.narration?.wps || [1.9, 3.4]);
  const rate = (wps[0] + wps[1]) / 2;
  const estimate = (text) => {
    const n = String(text || '').split(/\s+/).filter(Boolean).length;
    return n ? Math.max(1.2, n / rate) : 0;
  };

  const scenes = chapter.scenes.map((scene) => {
    const t = timing?.scenes?.[scene.id];
    let cursor = 0;
    const beats = scene.beats.map((beat) => {
      const bt = t?.beats?.find((b) => b.id === beat.id);
      const text = pick(beat.say, lang);
      const gapAfter = bt?.gapAfter ?? beat.gapAfter ?? 0;
      // Recorded beats carry their own start; estimated ones are laid end to
      // end, gaps included, so the scene has a real shape either way.
      const dur = bt?.dur ?? estimate(text);
      const start = bt?.start ?? cursor;
      cursor = start + dur + gapAfter;
      return {
        id: beat.id,
        text,
        start,
        dur,
        gapAfter,
        words: bt?.words ?? [],
        estimated: !bt,
        raw: beat,
      };
    });

    // Flatten every cue in the scene onto one timeline.
    const cues = [];
    for (const beat of beats) {
      beat.terms = [];
      for (const cue of beat.raw.cues || []) {
        // An anchor may be a bare string when it works in every language
        // (proper nouns usually do), or a {no, en} pair when the languages
        // say it differently — "syttisju" is "seventy-seven" over there.
        const on = pick(cue.on ?? 'start', lang);

        // `term.mark` is not a thing on the stage — it underlines a word in a
        // sentence — so it is resolved here and never reaches the cue list.
        // That is what keeps it outside rule 1: nothing to replay, nothing to
        // accumulate, and no card that could open forty times on a seek.
        if (cue.do === 'term.mark') {
          const i = resolveIndex(on, beat);
          if (i < 0) {
            warnings.push(`${beat.id}: term.mark "${cue.id}" is anchored to a word that is not in the text`);
          } else {
            beat.terms.push({
              i,
              span: Math.max(1, Math.min(6, cue.span ?? 1)),
              kind: cue.kind || 'term',
              id: cue.id,
            });
          }
          continue;
        }

        const at = resolve(on, beat, warnings);
        cues.push({ ...cue, t: at, beat: beat.id });
      }
    }
    // Stable sort: equal times keep their authored order, which matters when a
    // beat clears something and immediately sets it again.
    cues.forEach((c, i) => { c._i = i; });
    cues.sort((a, b) => (a.t - b.t) || (a._i - b._i));

    const last = beats[beats.length - 1];
    return {
      id: scene.id,
      title: pick(scene.title, lang),
      clock: pick(scene.clock, lang),
      audio: t ? `${base}/${t.audio}` : null,
      dur: t?.dur ?? (last ? last.start + last.dur + last.gapAfter : 0),
      beats,
      cues,
    };
  });

  if (warnings.length) {
    console.warn(`[script] ${warnings.length} cue anchor(s) could not be resolved:`);
    for (const w of warnings) console.warn('  ' + w);
  }

  return {
    id: chapter.id,
    pack: chapter.pack,
    lang,
    // The name of the whole work, not of this chapter. The cover leads with
    // it, because "19 April 1775" answers a question nobody has asked yet.
    // Falls back to the chapter title so a pack that never sets one still
    // shows something.
    work: pick(chapter.work, lang) || pick(chapter.title, lang),
    title: pick(chapter.title, lang),
    subtitle: pick(chapter.subtitle, lang),
    blurb: pick(chapter.blurb, lang),
    places: chapter.places || {},
    routes: chapter.routes || {},
    // Where region names resolve from, relative to the pack. compile() passes
    // an explicit whitelist rather than spreading the chapter, so anything a
    // scene needs has to be named here — leave it out and the cue silently
    // does nothing, which is exactly what happened the first time.
    regions: chapter.regions || null,
    // The pack manifest — factions, map framing, voices. In the whitelist for
    // the reason the comment above gives: leave it out and every faction
    // silently becomes the fallback colour.
    packInfo: chapter.packInfo || null,
    // The depth pools. In the whitelist for the reason above: leave one out
    // and every term marked against it silently opens nothing.
    terms: chapter.terms || {},
    topics: chapter.topics || {},
    placeNotes: chapter.placeNotes || {},
    people: chapter.people || [],
    media: chapter.media || {},
    quotes: chapter.quotes || {},
    poster: chapter.poster || null,
    // The words you hear and read are in `lang`; the surrounding UI is in
    // `uiLang`. They differ when a chapter has not been recorded in your
    // language yet, and the cover says so when that happens.
    uiLang,
    narrationLang: lang,
    dubbed: lang !== uiLang,
    scenes,
    duration: scenes.reduce((n, s) => n + s.dur, 0),
    hasAudio: Boolean(timing),
    warnings,
  };
}

function pick(field, lang) {
  if (field == null) return '';
  if (typeof field === 'string') return field;
  return field[lang] ?? field.no ?? field.en ?? '';
}

/* ------------------------------------------------------------
   Anchor resolution
   ------------------------------------------------------------ */

/** Strip punctuation and case so "Concord," matches "concord". */
function norm(s) {
  return String(s).toLowerCase().replace(/[^\p{L}\p{N}]/gu, '');
}

function resolve(on, beat, warnings) {
  const spec = on || ANCHOR.START;

  if (spec === ANCHOR.START) return beat.start;
  if (spec === ANCHOR.END) return beat.start + beat.dur;

  if (spec.startsWith('t:')) {
    return beat.start + (parseFloat(spec.slice(2)) || 0);
  }
  if (spec.startsWith('pct:')) {
    return beat.start + (parseFloat(spec.slice(4)) || 0) * beat.dur;
  }
  if (spec.startsWith('word:')) {
    // "word:Concord" or "word:Concord#2" for the second occurrence
    const [wanted, nth] = spec.slice(5).split('#');
    const target = norm(wanted);
    const want = Math.max(1, parseInt(nth || '1', 10));
    let seen = 0;
    for (const w of beat.words) {
      if (norm(w.w) === target && ++seen === want) return w.t;
    }
    warnings.push(`${beat.id}: no word "${wanted}"${nth ? ` #${nth}` : ''} in "${beat.text.slice(0, 60)}…"`);
    return beat.start;   // fall back to the beat opening rather than dropping it
  }

  warnings.push(`${beat.id}: unknown anchor "${spec}"`);
  return beat.start;
}

/**
 * Which written word a `word:` anchor points at.
 *
 * The sibling of resolve(), which answers "at what second" — this answers "at
 * which token", because a term has to be underlined in the caption rather
 * than fired on the timeline. Both walk the same anchor grammar, and both
 * count occurrences the same way, so `word:Boston#2` marks the same word it
 * would have fired on.
 *
 * Indexes the WRITTEN tokens, not the spoken ones: captions.js wraps
 * beat.text.split(/\s+/) so the punctuation survives, and that is the array a
 * span has to line up with.
 */
function resolveIndex(on, beat) {
  const spec = on || ANCHOR.START;
  const written = String(beat.text || '').split(/\s+/).filter(Boolean);
  if (!spec.startsWith('word:')) return spec === ANCHOR.END ? written.length - 1 : 0;
  const [wanted, nth] = spec.slice(5).split('#');
  const target = norm(wanted);
  const want = Math.max(1, parseInt(nth || '1', 10));
  let seen = 0;
  for (let i = 0; i < written.length; i += 1) {
    if (norm(written[i]) === target && ++seen === want) return i;
  }
  return -1;
}

/** Which beat is playing at time t (for captions). */
export function beatAt(scene, t) {
  let found = null;
  for (const b of scene.beats) {
    if (t >= b.start) found = b; else break;
  }
  return found;
}

/** Index of the word being spoken at time t, or -1 between words. */
export function wordAt(beat, t) {
  if (!beat) return -1;
  for (let i = 0; i < beat.words.length; i++) {
    const w = beat.words[i];
    if (t >= w.t && t < w.t + w.d + 0.06) return i;
    if (t < w.t) return i - 1;   // in the gap before this word
  }
  return beat.words.length - 1;
}
