#!/usr/bin/env python3
"""
Generate sound effects from text, and record where they came from.

    .venv-audio/Scripts/python.exe tools/gen-sound.py american-revolution --list
    .venv-audio/Scripts/python.exe tools/gen-sound.py american-revolution wind --candidates 3
    .venv-audio/Scripts/python.exe tools/gen-sound.py american-revolution wind --tag bare --prompt "…"
    .venv-audio/Scripts/python.exe tools/gen-sound.py american-revolution --accept wind-bare=2

Prompts live in content/<pack>/sound-prompts.json, versioned with the pack, so
"what did we ask for" survives the person who asked.

Candidates land in <project>/sound-candidates/<effect>/ — top level, one
folder per effect, with a looped and level-matched .mp3 beside every .wav so
they can be auditioned by double-clicking. The whole folder is gitignored.
Nothing enters the pack until you have listened and named one with --accept.


TWO BACKENDS, AND WHY
---------------------

  audiogen  (default)  Meta AudioGen medium. 16 kHz. Weights CC-BY-NC 4.0.
                       Runs in .venv-audio. ~25 s per clip on an RTX 4060.

  moss                 MOSS-SoundEffect v2.0. 48 kHz. Apache 2.0 — genuinely
                       commercial-safe, no attribution obligation. Runs in
                       .venv-moss. Fits 8 GB, but only with the dtype fix in
                       open_moss() below — read that comment before touching it.

MOSS is the better model on both axes that matter: a permissive licence and
three times the bandwidth. Measured on an RTX 4060 Laptop (8 GB): ~90 s for a
nine-second clip at 50 steps, 7.8 GB peak.

It very nearly got written off as needing a 24 GB card. The weights load at
10.61 GB because from_pretrained ignores torch_dtype for two of the three
components, Windows silently spills the excess to system RAM, and everything
crawls at 80 s/step while the GPU reports 100% utilisation at idle power. That
reads exactly like "too small a card" and is not. See open_moss().

The 16 kHz difference is not academic. A 16 kHz file cannot contain anything
above 8 kHz, and that is exactly where a bell's strike and a musket's crack
live — so AudioGen's bells come out dull no matter how the prompt is worded,
while its wind and hooves are excellent, because those have almost no energy
up there. Prefer the synthesised versions for anything with a sharp transient.


LICENCE
-------
An effect generated by `audiogen` is CC-BY-NC 4.0, which restricts using the
model for commercial ends — accepting one makes the build non-commercial. That
was a deliberate choice; see the first section of BACKLOG.md. `moss` output is
Apache 2.0 and carries no such restriction.

Beware: several blogs claim Meta's AudioCraft is Apache 2.0. It is not — its
repository says CC-BY-NC 4.0 for the weights. Check the LICENSE file of
anything before believing a summary of it. MOSS's Apache licence was confirmed
the same way, from the file rather than from a description of it.

Two rules this script keeps whichever backend runs:

  · every accepted entry is written with `licence` and `credit` filled in.
    sound/library.js refuses a file entry missing either, so an unattributed
    clip cannot reach a build by being present on disk.
  · it NEVER touches sound/library.js. The synthesised catalogue is the
    zero-dependency, zero-licence fallback and stays where it is; a pack entry
    only overrides it. Delete the entry and the synth comes back.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BACKENDS = {
    "audiogen": {
        "model": "facebook/audiogen-medium",
        "sr": 16000,
        "licence": "CC-BY-NC-4.0",
        "credit": "Generated with Meta AudioGen (facebook/audiogen-medium). "
                  "Model weights CC-BY-NC 4.0.",
        "venv": ".venv-audio",
    },
    "moss": {
        "model": "OpenMOSS-Team/MOSS-SoundEffect-v2.0",
        "sr": 48000,
        "licence": "Apache-2.0",
        "credit": "Generated with MOSS-SoundEffect v2.0 (OpenMOSS). Apache 2.0.",
        "venv": ".venv-moss",
    },
}

# MOSS is a diffusion model, so these exist only there. Defaults are the repo's.
STEPS = 50
CFG_SCALE = 4.0
SIGMA_SHIFT = 5.0

# How much tail is folded back over the head to make a loop join, in seconds.
# Same trick and the same reason as sound/library.js: cutting a bed at an
# arbitrary sample clicks.
SEAM = 0.30

# The SAME ceilings sound/library.js applies to every synthesised effect, and
# they have to be the same or the two halves of the catalogue sit at different
# levels — swap a synth effect for a generated one and the mix changes.
#
# Both a peak and an RMS ceiling, because either alone is wrong. Peak alone
# makes a sustained sound roughly ten times louder than a transient with the
# identical peak: a fife measured 0.38 RMS against a musket's 0.03. RMS alone
# lets a single transient clip. Whichever bites first wins.
#
# Generators normalise nothing, which is why the first generated hooves came
# out obviously quieter than everything around them.
PEAK = {"oneshot": 0.90, "loop": 0.55, "music": 0.50}
RMS = {"oneshot": 0.12, "loop": 0.11, "music": 0.10}


def die(msg: str) -> "None":
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(2)


def pack_paths(pack: str):
    d = os.path.join(ROOT, "content", pack)
    if not os.path.isdir(d):
        die(f"no pack at {d}")
    return {
        "dir": d,
        "prompts": os.path.join(d, "sound-prompts.json"),
        "sounds": os.path.join(d, "sound"),
        # Top level and named in plain English, NOT buried at
        # content/<pack>/sound/_candidates and certainly not in a temp
        # directory. These get opened by hand, over and over, for days.
        # Gitignored — only what --accept promotes into content/<pack>/sound/
        # is ever committed.
        "candidates": os.path.join(ROOT, "sound-candidates"),
        "manifest": os.path.join(d, "sound.json"),
    }


def load_prompts(p) -> dict:
    if not os.path.exists(p["prompts"]):
        die(f"no {os.path.relpath(p['prompts'], ROOT)} — see the docstring")
    with open(p["prompts"], encoding="utf-8") as fh:
        return json.load(fh)


def write_wav(path, wav, sr):
    """Write a (channels, samples) tensor.

    soundfile rather than torchaudio.save: torchaudio 2.9 delegates saving to
    torchcodec, which is a separate install and is not in either venv — and
    the failure lands AFTER generation, so you lose the clip you just spent
    ninety seconds making. soundfile is already here for both backends.
    """
    import soundfile as sf
    sf.write(path, wav.T.numpy(), sr, subtype="PCM_16")


def read_wav(path):
    """Returns a (channels, samples) float tensor and the sample rate."""
    import soundfile as sf
    import torch
    data, sr = sf.read(path, dtype="float32", always_2d=True)
    return torch.from_numpy(data).T.contiguous(), int(sr)


def write_audition(wav_path, kind):
    """An mp3 beside the wav, for listening rather than for shipping.

    Two things it does that raw playback does not: loops are repeated three
    times so the join is audible, and everything is loudness-matched, so a
    comparison is about character rather than about which candidate happened
    to come out louder. Generators normalise nothing — the first hooves batch
    was judged "too quiet" when the real difference was a level, not a sound.

    Written next to the wav in <project>/sound-candidates/<effect>/ rather
    than a temp directory, because these get listened to repeatedly over days
    and hunting for them in AppData is nobody's idea of a good time.
    """
    import shutil
    import subprocess
    if not shutil.which("ffmpeg"):
        return None
    out = wav_path[:-4] + ".mp3"
    loop = ["-stream_loop", "2"] if kind != "oneshot" else []
    try:
        subprocess.run(
            ["ffmpeg", "-y", "-loglevel", "error", *loop, "-i", wav_path,
             "-af", "loudnorm=I=-18:TP=-1.5:LRA=11",
             "-codec:a", "libmp3lame", "-q:a", "5", out],
            check=True)
        return out
    except (subprocess.CalledProcessError, OSError):
        return None


def as_wav(audio):
    """Whatever a backend returned, as a float (channels, samples) tensor."""
    import torch
    wav = audio if torch.is_tensor(audio) else torch.as_tensor(audio)
    wav = wav.detach().float().cpu()
    if wav.dim() == 1:
        wav = wav.unsqueeze(0)
    elif wav.dim() == 3:
        wav = wav[0]
    # Long axis is time. A tensor arriving as (samples, channels) is common
    # enough that guessing from the shape beats trusting the docs.
    if wav.shape[0] > wav.shape[1]:
        wav = wav.T
    return wav


# ------------------------------------------------------------------
# Backends. Each returns a callable (prompt, seconds, seed) -> tensor.
# ------------------------------------------------------------------

def open_audiogen(cfg, steps, cfg_scale):
    import torch
    from audiocraft.models import AudioGen
    model = AudioGen.get_pretrained(cfg["model"])

    def run(prompt, seconds, seed):
        torch.manual_seed(seed)
        model.set_generation_params(duration=seconds)
        return model.generate([prompt])[0]

    return run, int(model.sample_rate)


def open_moss(cfg, steps, cfg_scale):
    # torch.compile needs Triton, which is Linux-only; on Windows the pipeline
    # dies with TritonMissing partway through the first clip. Eager is slower
    # but has nothing to install and nothing to go stale.
    os.environ.setdefault("TORCHDYNAMO_DISABLE", "1")
    import torch
    torch._dynamo.config.suppress_errors = True
    from huggingface_hub import snapshot_download
    from moss_soundeffect_v2 import MossSoundEffectPipeline

    pipe = MossSoundEffectPipeline.from_pretrained(
        snapshot_download(cfg["model"], resume_download=True),
        torch_dtype=torch.bfloat16, device="cuda")
    eng = pipe.engine

    # THE thing that makes this run on 8 GB, and it is not obvious.
    #
    # from_pretrained(torch_dtype=bfloat16) is honoured for the text encoder
    # and SILENTLY IGNORED for the DiT and the VAE, which load in float32:
    #
    #     text_encoder  1721M  3.44 GB  bfloat16
    #     vae            372M  1.49 GB  float32
    #     dit           1416M  5.68 GB  float32   <- 2.84 GB of pure waste
    #     TOTAL               10.61 GB  on an 8.2 GB card
    #
    # Over the card before a single activation, so Windows spilled the excess
    # into system RAM over PCIe and every denoising step waited on the bus:
    # 80 s/step, with the GPU reporting 100% utilisation at 25 W — idle power.
    # Casting the DiT alone takes it to 7.78 GB and 1.4 s/step. Fifty-seven
    # times faster, same output.
    #
    # Parameters only, never buffers: this DiT keeps its rotary-embedding
    # frequencies as a COMPLEX buffer, and a blanket .to(bfloat16) makes
    # freqs.imag throw "imag is not implemented for tensors with non-complex
    # dtypes" on the first attention call. All the memory is in the weights
    # anyway.
    for p in eng.dit.parameters(recurse=True):
        if p.dtype == torch.float32:
            p.data = p.data.to(torch.bfloat16)
    torch.cuda.empty_cache()

    # The VAE stays float32 on purpose: only 1.5 GB, it runs once at decode,
    # and an audio decoder is the part of a pipeline most likely to show
    # artefacts in half precision.
    eng.enable_cpu_offload()

    def run(prompt, seconds, seed):
        return pipe(prompt=prompt, seconds=seconds, num_inference_steps=steps,
                    cfg_scale=cfg_scale, sigma_shift=SIGMA_SHIFT, seed=seed)

    return run, int(getattr(pipe, "sample_rate", cfg["sr"]))


OPENERS = {"audiogen": open_audiogen, "moss": open_moss}


# ------------------------------------------------------------------
# Generation
# ------------------------------------------------------------------

def generate(pack: str, effect: str, n: int, seed_base: int, backend: str,
             prompt: str = None, tag: str = None, duration: float = None,
             steps: int = STEPS, cfg_scale: float = CFG_SCALE) -> int:
    cfg = BACKENDS[backend]
    p = pack_paths(pack)
    prompts = load_prompts(p)
    if effect not in prompts:
        die(f"no prompt for '{effect}' in {os.path.relpath(p['prompts'], ROOT)}")
    spec = prompts[effect]
    # --prompt tries wording the pack file does not commit to yet. Several
    # seeds of one prompt explore a much smaller space than several prompts
    # do, and the wording is usually what is wrong. --tag keeps the variants
    # apart on disk so you can audition them side by side.
    text = prompt or spec["prompt"]
    dur = float(duration if duration is not None else spec.get("duration", 5))
    kind = spec.get("kind", "oneshot")
    stem = f"{effect}-{tag}" if tag else effect

    # Loops are asked for SEAM seconds longer than they need, so there is real
    # material to fold back over the head. Exactly what library.js does.
    render = dur + (SEAM if kind != "oneshot" else 0)

    outdir = os.path.join(p["candidates"], effect)   # one folder per effect
    os.makedirs(outdir, exist_ok=True)

    print(f"loading {cfg['model']} …", flush=True)
    t0 = time.time()
    run, sr = OPENERS[backend](cfg, steps, cfg_scale)
    print(f"  loaded in {time.time() - t0:.0f}s, {sr} Hz", flush=True)

    print(f'\n{effect}: "{text}"')
    print(f"  {n} candidates, {render:.1f}s each, kind={kind}, backend={backend}\n",
          flush=True)

    for i in range(1, n + 1):
        seed = seed_base + i     # fixed per index, so "candidate 3" is stable
        t0 = time.time()
        wav = as_wav(run(text, render, seed))
        out = os.path.join(outdir, f"{stem}-{i}.wav")
        write_wav(out, wav, sr)
        # A sidecar per candidate, because --accept is a separate invocation
        # and cannot otherwise know what produced the file. Without it a
        # candidate generated from an overridden prompt would be filed under
        # the pack's wording, and the manifest would confidently record a
        # prompt that never made this sound.
        side = {"prompt": text, "duration": dur, "kind": kind, "seed": seed,
                "backend": backend, "model": cfg["model"],
                "licence": cfg["licence"], "sampleRate": sr}
        if backend == "moss":
            side.update(steps=steps, cfgScale=cfg_scale, sigmaShift=SIGMA_SHIFT)
        with open(out[:-4] + ".json", "w", encoding="utf-8", newline="\n") as fh:
            json.dump(side, fh, ensure_ascii=False, indent=2)
        mp3 = write_audition(out, kind)
        print(f"  [{i}/{n}] {os.path.basename(out):<28} {time.time() - t0:5.0f}s"
              f"  peak {wav.abs().max().item():.2f}"
              f"{'  + mp3' if mp3 else '  (no ffmpeg — wav only)'}", flush=True)

    print(f"\nListen — play the .mp3 files (looped and level-matched):")
    print(f"  {outdir}")
    print(f"\nAccept: python tools/gen-sound.py {pack} --accept {stem}=<n>")
    if tag:
        print(f"        (filed as '{effect}' — the tag only names the candidate)")
    return 0


# ------------------------------------------------------------------
# Accepting one into the pack
# ------------------------------------------------------------------

def seam_loop(wav, sr: int, dur: float):
    """Fold the overhang back over the head with an equal-power crossfade.

    A generated clip has no reason to join itself, and a bed that clicks once
    a loop is worse than a bed that is slightly wrong. Same approach as the
    synthesised loops, so the two sound like they belong to one library.
    """
    import torch
    keep = int(dur * sr)
    seam = min(int(SEAM * sr), keep, wav.shape[-1] - keep)
    if seam <= 0:
        return wav[..., :keep]
    out = wav[..., :keep].clone()
    tail = wav[..., keep:keep + seam]
    w = torch.linspace(0, 1, seam)
    out[..., :seam] = out[..., :seam] * w.sqrt() + tail * (1 - w).sqrt()
    return out


def normalise(wav, kind: str):
    """Bring a clip to the same ceilings library.js gives every synth effect.

    Peak-and-RMS rather than perceptual loudness (LUFS), deliberately: matching
    what the synthesised half of the catalogue already does matters more than
    being perceptually ideal, because the two are interchangeable at runtime
    and a level jump on swapping one for the other is the actual bug.
    """
    peak = wav.abs().max().item()
    rms = wav.pow(2).mean().sqrt().item()
    head_peak = (PEAK.get(kind, 0.8) / peak) if peak > 1e-4 else 1.0
    head_rms = (RMS.get(kind, 0.11) / rms) if rms > 1e-4 else 1.0
    k = min(head_peak, head_rms)
    return wav * k, {
        "gain": k,
        "peakBefore": peak, "rmsBefore": rms,
        "peakAfter": peak * k, "rmsAfter": rms * k,
        "bound": "peak" if head_peak <= head_rms else "rms",
    }


def accept(pack: str, effect: str, which: int) -> int:
    p = pack_paths(pack)
    prompts = load_prompts(p)
    # A tagged candidate is still an override for the base effect: 'wind-bare'
    # is a wind, and the engine only knows the name 'wind'.
    base = effect.split("-", 1)[0] if effect not in prompts else effect
    spec = prompts.get(base) or die(f"no prompt for '{base}'")
    src = os.path.join(p["candidates"], base, f"{effect}-{which}.wav")
    if not os.path.exists(src):
        die(f"no candidate at {os.path.relpath(src, ROOT)} — generate first")

    # What actually produced this file, not what the pack file happens to say
    # now. The two differ whenever --prompt was used, and the whole reason the
    # manifest carries a prompt is so somebody can regenerate this sound.
    side = {}
    if os.path.exists(src[:-4] + ".json"):
        with open(src[:-4] + ".json", encoding="utf-8") as fh:
            side = json.load(fh)
    backend = side.get("backend", "audiogen")
    cfg = BACKENDS.get(backend, BACKENDS["audiogen"])

    wav, sr = read_wav(src)
    kind = side.get("kind", spec.get("kind", "oneshot"))
    if kind != "oneshot":
        wav = seam_loop(wav, sr, float(side.get("duration", spec.get("duration", 5))))
    # After the seam, not before: the crossfade changes both peak and RMS.
    wav, lvl = normalise(wav, kind)

    os.makedirs(p["sounds"], exist_ok=True)
    dest = os.path.join(p["sounds"], f"{base}.wav")
    write_wav(dest, wav, sr)

    manifest = {}
    if os.path.exists(p["manifest"]):
        with open(p["manifest"], encoding="utf-8") as fh:
            manifest = json.load(fh)

    # Everything a DIFFERENT subject would need to find and judge this file
    # without listening to it. A sound effect is the most reusable thing in
    # this repo — a market in Bergen and a mob in Boston are the same crowd —
    # but only if the next pack can search for it.
    manifest[base] = {
        "file": f"sound/{base}.wav",
        "title": spec.get("title", {"no": base, "en": base}),
        "description": spec.get("description", ""),
        "tags": spec.get("tags", []),
        "reuse": spec.get("reuse", "subject"),
        "kind": kind,
        "duration": round(wav.shape[-1] / sr, 2),
        "licence": side.get("licence", cfg["licence"]),
        "credit": cfg["credit"],
        "source": f"https://huggingface.co/{side.get('model', cfg['model'])}",
        "prompt": side.get("prompt", spec["prompt"]),
        "seed": side.get("seed"),
        "sampleRate": sr,
        "levelled": {k: (round(v, 4) if isinstance(v, float) else v)
                     for k, v in lvl.items()},
        "candidate": f"{effect}-{which}",
    }
    with open(p["manifest"], "w", encoding="utf-8", newline="\n") as fh:
        json.dump(manifest, fh, ensure_ascii=False, indent=2)
        fh.write("\n")

    kb = os.path.getsize(dest) // 1024
    print(f"accepted {base} <- candidate {effect}-{which}  [{backend}]")
    print(f"  {os.path.relpath(dest, ROOT)}  {kb} KB  {kind}  {sr} Hz")
    print(f"  levelled x{lvl['gain']:.2f} ({lvl['bound']}-bound): "
          f"peak {lvl['peakBefore']:.2f}->{lvl['peakAfter']:.2f}  "
          f"rms {lvl['rmsBefore']:.4f}->{lvl['rmsAfter']:.4f}")
    print(f"  {os.path.relpath(p['manifest'], ROOT)}  {len(manifest)} entr(ies)")
    print("\nNext:")
    print("  · add the file to PRECACHE in sw.js and bump VERSION")
    print("  · python tools/check-script.py <pack>/<chapter>   (validates the manifest)")
    if BACKENDS[backend]["licence"].startswith("CC-BY-NC"):
        print(f"\n  ! {base} is CC-BY-NC. This build is not commercially usable.")
        print("    Remove the entry from sound.json and the synthesised effect returns.")
    return 0


def show_list(pack: str) -> int:
    p = pack_paths(pack)
    prompts = load_prompts(p)
    have = {}
    if os.path.exists(p["manifest"]):
        with open(p["manifest"], encoding="utf-8") as fh:
            have = json.load(fh)
    print(f"{'effect':<14} {'kind':<9} {'dur':>5}  in pack  prompt")
    for name, spec in prompts.items():
        if name.startswith("_"):        # _note and friends are documentation
            continue
        mark = "yes" if name in have else " - "
        print(f"{name:<14} {spec.get('kind','oneshot'):<9} "
              f"{float(spec.get('duration',5)):5.1f}  {mark:^7}  {spec['prompt'][:52]}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("pack")
    ap.add_argument("effect", nargs="?", help="which effect to generate")
    ap.add_argument("--backend", choices=sorted(BACKENDS), default="audiogen")
    ap.add_argument("--candidates", type=int, default=3)
    ap.add_argument("--seed", type=int, default=1000)
    ap.add_argument("--accept", metavar="EFFECT=N",
                    help="move a candidate into the pack and write sound.json")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--prompt", help="override the pack's wording for this run")
    ap.add_argument("--tag", help="name these candidates apart, e.g. --tag bare")
    ap.add_argument("--duration", type=float)
    ap.add_argument("--steps", type=int, default=STEPS, help="moss only")
    ap.add_argument("--cfg", type=float, default=CFG_SCALE, help="moss only")
    a = ap.parse_args()

    if a.list:
        return show_list(a.pack)
    if a.accept:
        if "=" not in a.accept:
            die("--accept wants EFFECT=N, e.g. --accept wind-bare=2")
        name, n = a.accept.split("=", 1)
        return accept(a.pack, name, int(n))
    if not a.effect:
        return show_list(a.pack)
    return generate(a.pack, a.effect, a.candidates, a.seed, a.backend,
                    prompt=a.prompt, tag=a.tag, duration=a.duration,
                    steps=a.steps, cfg_scale=a.cfg)


if __name__ == "__main__":
    sys.exit(main())
